export const applicationList = [
    "appender",
    "archiver",
    "chat",
    "clippings",
    "collage",
    "edit",
    "filer",
    "ibis",
    "ideas",
    "mail",
    "monitor",
    "notebook",
    "notes",
    "outliner",
    "search",
    "sketcher",
    "tables",
    "triples",
    "twirlip",
    "view-md",
]

export const extensionForApplication = {
    chat: ".twirlip-chat.jsonl",
    collage: ".twirlip-collage.jsonl",
    edit: ".txt",
    ibis: ".twirlip-ibis.jsonl",
    notebook: ".twirlip-notebook.jsonl",
    outliner: ".twirlip-outliner.jsonl",
    sketcher: ".twirlip-sketcher.jsonl",
    tables: ".twirlip-tables.jsonl",
    triples: ".twirlip-triples.jsonl",
    twirlip: ".twirlip.jsonl",
}